name: pizza_delivery
description: A pizza delivery application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  flutter_svg: ^0.17.3+1
  provider: ^4.0.4
  quiver: ^2.0.5
  path: ^1.6.4
  sqflite: ^1.3.0
  google_maps_flutter: ^0.5.26+2
  http: ^0.12.0+4
  camera: ^0.5.7+4
  path_provider: ^1.6.7
  contacts_service: ^0.4.5
  permission_handler: ^5.0.0+hotfix.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  matcher: ^0.12.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/favourites.svg
    - images/pizza.svg
    - images/profile.svg
    - images/delivery-truck.svg
    - images/box.svg
    - images/chili.svg
    - images/ham.svg
    - images/salami.svg
    - images/tomato.svg
    - images/mozzarella.svg
    - images/unknown.svg
    - images/pizza-ham-salami.jpg
    - images/pizza-ham.jpg
    - images/pizza-margherita.jpg
    - images/pizza-pepperoni.png
    - images/pizza-salami.jpg
    - images/pizza-veggie.jpg
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
